name: c-i

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test Projects and Pipelines
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64
          - x86_64
    permissions:
      contents: read
    runs-on: ubuntu-24.04-${{matrix.arch}}
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: chainguard-dev/actions/apt-faster@e1c4977ad9cb32b12c5b222ec0134a22bec60bd5 # v1.6.25
      - uses: chainguard-dev/actions/setup-melange@e1c4977ad9cb32b12c5b222ec0134a22bec60bd5 # v1.6.25
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: './go.work'
          cache-dependency-path: '**/*.sum'
      - name: Setup shellcheck
        uses: ./.github/actions/shellcheck
        with:
          version: v0.10.0
      - name: lint
        run: make lint
      - name: Build
        run: make build
      - name: Test all projects
        run: |
          make test-projects
      - name: Test in melange
        run: |
          make test-melange
      - name: Test pipeline validations
        run: |
          make test-pipelines
